apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o9i5atb9c-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:4f0a8dce44e818579ec8a04055e9dd1f0969ad93@sha256:e50cfb01acde626e903b6b91744e4ccc3d1e40f2635a92cf5fc8228560fbd222
          name: container-image
