apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: o9i5atb9c-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/o9i5atb9c-java-springboot-gitops